# Trigger pipeline when changes are pushed to the main branch
trigger:
- main

# Use the latest Ubuntu image for the build agent
pool:
  vmImage: ubuntu-latest

# Steps to run the pipeline
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Set up Python'

# Checkout the repository
- checkout: self
  displayName: 'Checkout code from GitHub'

# Install dependencies (e.g., from requirements.txt)
- script: |
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Run tests (assuming you have pytest or any other testing framework)
- script: |
    source venv/bin/activate
    pytest tests/
  displayName: 'Run Tests'

# Run the Python script (app1.py)
- script: |
    source venv/bin/activate
    python app1.py
  displayName: 'Run app1.py'

# Optional: Add a step to deploy or package the application
# - script: |
#     echo Deploy or package the application here
#   displayName: 'Deploy the app'

